### ISSUE TITLE
utilising several images

### ISSUE THREAD

**Issue by eemrys** [fuenwang/LED2-Net#2]
hi! i have several panoramic images of the same place and i would like to utilise them together to estimate the layout. or maybe somehow merge the estimated layouts from each image to create the final layout. obviously it’s not part of your project but maybe you can give me some advice/ideas on how to do that? thanks!

**Comment by fuenwang** [comment]
To merge the layout, there may be several issues:

1. The scale of each room could be different, i.e, fixing camera height to 1.6 by layout labeling tool like [this](https://github.com/SunDaDenny/PanoAnnotator) will cause errors when you combine them together. However, if you can fix the camera height when capturing all images, this can be naturally solved.
2. The simplest way to merge them is to build your own merging tool with opengl and move the layouts to correct positions by yourself.

**Comment by marcomiglionico94** [comment]
> To merge the layout, there may be several issues:
> 
> 1. The scale of each room could be different, i.e, fixing camera height to 1.6 by layout labeling tool like [this](https://github.com/SunDaDenny/PanoAnnotator) will cause errors when you combine them together. However, if you can fix the camera height when capturing all images, this can be naturally solved.
> 2. The simplest way to merge them is to build your own merging tool with opengl and move the layouts to correct positions by yourself.

Hi is it possible to export the final model into a point cloud or mesh file?
